
- name: install dependencies
  apt:
    name: [ ca-certificates, curl, gnupg]
    update_cache: true
    state: latest
- name: install keyrings
  command: install -m 0755 -d /etc/apt/keyrings
- name: get gpg keyr
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
- name: add repository to apt sources
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
- name: install docker
  apt: 
    name: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]
    update_cache: true
    state: latest
- name: Add user {{ user }} to docker group
  user:
    append: true
    groups: ["docker"]
    name: "{{ user }}"