on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-front:
    name: Build and deploy on github registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Login to registry"
        run: |
          export CR_PAT=$TOKEN
          echo $CR_PAT | docker login -u quentinlegot --password-stdin
        env:
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: "Compile and push front"
        run: |
          cd front
          docker build -t quentinlegot/tlc-front:latest .
          docker push quentinlegot/tlc-front:latest
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Login to registry"
        run: |
          export CR_PAT=$TOKEN
          echo $CR_PAT | docker login -u quentinlegot --password-stdin
        env:
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: "Compile and push api"
        run: |
          cd api
          docker build -t quentinlegot/tlc-api:latest .
          docker push quentinlegot/tlc-api:latest
  build-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Login to registry"
        run: |
          export CR_PAT=$TOKEN
          echo $CR_PAT | docker login -u quentinlegot --password-stdin
        env:
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: "Compile and push db"
        run: |
          cd db
          docker build -t quentinlegot/tlc-db:latest .
          docker push quentinlegot/tlc-db:latest
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    needs: [ build-front, build-api, build-db ]
    steps:
      - uses: actions/checkout@v4
      # - name: Install ansible
      #   run: apt update -y && apt install -y ansible # do need to install, already done on runner
      - name: Add password to a file
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_PASS: ${{ secrets.VM_PASSWORD }}
          VM_IP: ${{ secrets.VM_IP }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_ROOT_PASS: ${{ secrets.DB_ROOT_PASS }}
        run: |
          cd ansible
          mkdir host_vars
          touch "${VM_IP}.yml"
          echo "vault_ansible_ssh_user: ${VM_USER}" >> "host_vars/${VM_IP}.yml"
          echo "vault_ansible_ssh_pass: ${VM_PASS}" >> "host_vars/${VM_IP}.yml"
          echo "vault_pass: ${DB_PASS}" >> "host_vars/${VM_IP}.yml"
          echo "vault_root_pass: ${DB_ROOT_PASS}" >> "host_vars/${VM_IP}.yml"
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with: 
          playbook: deploy.yml
          directory: ./ansible
          options: |
            -i hosts
          
      
      
    
